# Generated by Django 5.0.6 on 2024-11-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_endstop_busschadule'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstop',
            name='start',
            field=models.BooleanField(default=False),
        ),
    ]
