# Generated by Django 5.0.6 on 2024-11-18 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_busstop_start'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BusSchadule',
            new_name='BusSchedule',
        ),
    ]
