# Generated by Django 5.0.6 on 2024-11-18 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_busschadule_busschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busschedule',
            old_name='araival',
            new_name='arrival',
        ),
    ]
