# Generated by Django 5.1.3 on 2024-11-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='stop',
        ),
        migrations.AddField(
            model_name='history',
            name='end',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='start',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
