# Generated by Django 5.1.3 on 2024-12-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_history_distance_history_end_loc_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endstop',
            name='route_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
